node('docker') {
    stage 'Checkout from Github'
        checkout scm
    stage 'Build Spark images with python and pyspark package'
        sh "cd /home/jenkins/workspace/testing/Spark-Docker/;./build-images.sh"
    stage 'Integration Test'
        sh "docker-compose -f /home/jenkins/workspace/testing/Spark-Docker/docker-compose.yml up --force-recreate -d"
    stage 'Acceptance Testing'
    sleep(time:10,unit:"SECONDS")
        sh "python /home/jenkins/workspace/testing/Spark-Docker/Pi.py"
    stage 'Shutdown Spark containers'
        sh "docker-compose -f /home/jenkins/workspace/testing/Spark-Docker/docker-compose.yml down -v"
    stage 'Remove Spark docker images'
        sh "docker image rm $(docker image ls | grep spark | awk '{ print $3}')"
}
