node('docker') {
 
    stage 'Checkout'
        checkout scm
    stage 'Run build-images.sh'
        sh "cd /home/jenkins/workspace/testing/Spark-Docker/;./build-images.sh"
    stage 'Integration Test'
        sh "docker-compose -f /home/jenkins/workspace/testing/Spark-Docker/docker-compose.yml up --force-recreate -d"
        sh "docker-compose -f /home/jenkins/workspace/testing/Spark-Docker/docker-compose.yml down -v"
}
