---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: spark-master-1
  labels:
    app: spark-master-1
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
  - name: "7077"
    port: 7077
  selector:
    app: spark-master-1
---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: spark-worker-1
  labels:
    app: spark-worker-1
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: "8081"
    port: 8081
  selector:
    app: spark-worker-1
---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: spark-worker-2
  labels:
    app: spark-worker-2
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: "8081"
    port: 8081
  selector:
    app: spark-worker-2
---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: spark-worker-3
  labels:
    app: spark-worker-3
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: "8081"
    port: 8081
  selector:
    app: spark-worker-3
