apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: spark-master-1
    name: spark-master-1
  spec:
    clusterIP: "None"
    type: ClusterIP
    ports:
    - name: "8080"
      port: 8080
    - name: "7077"
      port: 7077
    selector:
      app: spark-master-1
kind: List
metadata: {}
