apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: spark-master
  labels:
    app: "spark-master-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master-1
  template:
    metadata:
      labels:
        app: spark-master-1
    spec:
      hostname: spark-master-1
      containers:
      - name: spark-master
        imagePullPolicy: Never
        image: spark-master:2.4.3
        ports:
        - name: webui
          containerPort: 8080
        - name: driver
          containerPort: 7077
        volumeMounts:
        - mountPath: /opt/spark-apps
          subPath: spark-apps
          name: nfs-spark
        - mountPath: /opt/spark-data
          subPath: spark-data
          name: nfs-spark
      volumes:
      - name: nfs-spark
        persistentVolumeClaim:
          claimName: nfs-docker-spark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: spark-worker-1
  labels:
    app: "spark-worker-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-1
  template:
    metadata:
      labels:
        app: spark-worker-1
    spec:
      containers:
      - name: spark-worker-1
        imagePullPolicy: Never
        image: spark-worker:2.4.3
        env:
        - name: SPARK_DRIVER_MEMORY
          valueFrom:
            configMapKeyRef:
              name: spark-worker-1-env
              key: SPARK_DRIVER_MEMORY
        - name: SPARK_EXECUTOR_MEMORY
          valueFrom:
            configMapKeyRef:
              name: spark-worker-1-env
              key: SPARK_EXECUTOR_MEMORY
        - name: SPARK_MASTER
          valueFrom:
            configMapKeyRef:
              name: spark-worker-1-env
              key: SPARK_MASTER
        - name: SPARK_WORKER_CORES
          valueFrom:
            configMapKeyRef:
              name: spark-worker-1-env
              key: SPARK_WORKER_CORES
        - name: SPARK_WORKER_MEMORY
          valueFrom:
            configMapKeyRef:
              name: spark-worker-1-env
              key: SPARK_WORKER_MEMORY
        ports:
        - name: webui
          containerPort: 8081
        volumeMounts:
        - mountPath: /opt/spark-apps
          subPath: spark-apps
          name: nfs-spark
        - mountPath: /opt/spark-data
          subPath: spark-data
          name: nfs-spark
      volumes:
      - name: nfs-spark
        persistentVolumeClaim:
          claimName: nfs-docker-spark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: spark-worker-2
  labels:
    app: "spark-worker-2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-2
  template:
    metadata:
      labels:
        app: spark-worker-2
    spec:
      containers:
      - name: spark-worker-2
        imagePullPolicy: Never
        image: spark-worker:2.4.3
        env:
        - name: SPARK_DRIVER_MEMORY
          valueFrom:
            configMapKeyRef:
              name: spark-worker-2-env
              key: SPARK_DRIVER_MEMORY
        - name: SPARK_EXECUTOR_MEMORY
          valueFrom:
             configMapKeyRef:
               name: spark-worker-2-env
               key: SPARK_EXECUTOR_MEMORY
        - name: SPARK_MASTER
          valueFrom:
            configMapKeyRef:
              name: spark-worker-2-env
              key: SPARK_MASTER
        - name: SPARK_WORKER_CORES
          valueFrom:
            configMapKeyRef:
              name: spark-worker-2-env
              key: SPARK_WORKER_CORES
        - name: SPARK_WORKER_MEMORY
          valueFrom:
            configMapKeyRef:
              name: spark-worker-2-env
              key: SPARK_WORKER_MEMORY
        ports:
        - name: webui
          containerPort: 8081
        volumeMounts:
        - mountPath: /opt/spark-apps
          subPath: spark-apps
          name: nfs-spark
        - mountPath: /opt/spark-data
          subPath: spark-data
          name: nfs-spark
      volumes:
      - name: nfs-spark
        persistentVolumeClaim:
          claimName: nfs-docker-spark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: spark-worker-3
  labels:
    app: "spark-worker-3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-3
  template:
    metadata:
      labels:
        app: spark-worker-3
    spec:
      containers:
      - name: spark-worker-3
        imagePullPolicy: Never
        image: spark-worker:2.4.3
        env:
        - name: SPARK_DRIVER_MEMORY
          valueFrom:
            configMapKeyRef:
              name: spark-worker-3-env
              key: SPARK_DRIVER_MEMORY
        - name: SPARK_EXECUTOR_MEMORY
          valueFrom:
             configMapKeyRef:
               name: spark-worker-3-env
               key: SPARK_EXECUTOR_MEMORY
        - name: SPARK_MASTER
          valueFrom:
            configMapKeyRef:
              name: spark-worker-3-env
              key: SPARK_MASTER
        - name: SPARK_WORKER_CORES
          valueFrom:
            configMapKeyRef:
              name: spark-worker-3-env
              key: SPARK_WORKER_CORES
        - name: SPARK_WORKER_MEMORY
          valueFrom:
            configMapKeyRef:
              name: spark-worker-3-env
              key: SPARK_WORKER_MEMORY
        ports:
        - name: webui
          containerPort: 8081
        volumeMounts:
        - mountPath: /opt/spark-apps
          subPath: spark-apps
          name: nfs-spark
        - mountPath: /opt/spark-data
          subPath: spark-data
          name: nfs-spark
      volumes:
      - name: nfs-spark
        persistentVolumeClaim:
          claimName: nfs-docker-spark
---
