apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: spark-master
  labels:
    app: "spark-master-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master-1
  template:
    metadata:
      labels:
        app: spark-master-1
    spec:
      containers:
      - name: spark-master
        imagePullPolicy: Never
        image: spark-master:2.4.3
        ports:
        - name: webui
          containerPort: 8080
        - name: driver
          containerPort: 7077
        volumeMounts:
        - mountPath: /opt/spark-apps
          subPath: spark-apps
          name: nfs-spark
        - mountPath: /opt/spark-data
          subPath: spark-data
          name: nfs-spark
      volumes:
      - name: nfs-spark
        persistentVolumeClaim:
          claimName: nfs-docker-spark
---
